import styles from "../styles/Home.module.scss";

import type { NextPage } from "next";
import Head from "next/head";
import { Title, Image, Group } from "@mantine/core";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Patato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="fullflex">
        <section className={styles.container}>
          <Group position="apart">
            <div>
              <Title className={styles.intro}>Hi, my name is</Title>
              <Title className="name" color="#ffa64a">
                Pat <span className="subname">( Patato )</span>
              </Title>
            </div>
            <div className={styles.pfpimage}>
              <Image
                width={130}
                height={130}
                src="/pfp.jpg"
                alt="Profile Picture"
                radius="md"
              />
            </div>
          </Group>

          <p>
            I’m a full-stack developer who likes creating fun software and
            websites
          </p>
        </section>
      </main>
    </>
  );
};

export default Home;
